version: "3"

services:
    api:
        build:
            context: backend
            dockerfile: Dockerfile
            target: dev
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
