version: "3"

services:
    api:
        build:
            context: backend
            dockerfile: Dockerfile
            target: dev
            args:
                - USER_UID=${USER_UID}
                - USER_GID=${USER_GID}
                - USERNAME=${USERNAME}
        env_file:
            - .env

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
